export const GET_CONVERSION_RATE = {
    SUCCESS:"GET_CONVERSION_RATE_SUCCESS",
    LOADING:"GET_CONVERSION_RATE_LOADING",
    ERROR:"GET_CONVERSION_RATE_ERROR",
    EXCHANGE:"GET_CONVERSION_RATE_EXCHANGE",
}